HERO Toolchain v2.0.0 (updated 12-7-2018)
 ### Added:
 - New repo structure:
	- Builder utilities and tools are now stored in a new folder `bin`.
	- `bin/*` utilities are installed to the `$PATH` using by the `setup.sh`.
	- `install` folder is moved to `pkg/hero-gcc-toolchain`.
	- `build` folder is moved to `pkg/build`.
 - New `bin/hero_toolchain_artifact` tool for create/deploy/download artifacts.
 - New `bin/hero_toolchain_build` tool for build the toolchain. It integrates in a single tool the removed `hero_riscv32_toolchain_builder` and `hero_arm_toolchain_builder`.
 - New `bin/hero_toolchain_installer` tool for board installation of the toolchain.
 - New `bin/hero_toolchain_update_sources` tool for fast update of submodules.

 ### Removed:
 - `hero_riscv32_toolchain_builder` integrated into `bin/hero_toolchain_build`.
 - `hero_arm_toolchain_builder` integrated into `bin/hero_toolchain_build`.
 - `scripts/hero_riscv32_toolchain_env.sh` integrated into `env/hero_toolchain_env.sh`.
 - `scripts/hero_arm_toolchain_env.sh` integrated into `env/hero_toolchain_env.sh`.
 - `scripts/install_toolchain.sh` integrated into `bin/hero_toolchain_installer`.
 - `scripts/hero_toolchain_get_sources.sh` integrated into `env/hero_toolchain_update_sources`.

 ### Changed:
 - Update `src/riscv-gcc`, `src/binutils`, and `src/newlib` submodules.

diff --git a/bin/hero_toolchain_installer b/bin/hero_toolchain_installer
--- a/bin/hero_toolchain_installer
+++ b/bin/hero_toolchain_installer
@@ -15,24 +15,29 @@
 #
 # Authors: Alessandro Capotondi, University of Bologna (alessandro.capotondi@unibo.it)
 
-source ${HERO_TOOLCHAIN_DIR}/scripts/hero_arm_toolchain_env.sh
-source ${HERO_TOOLCHAIN_DIR}/scripts/hero_riscv32_toolchain_env.sh
+
+# Setup the envioronmental variables
+if [ -z "${HERO_TOOLCHAIN_DIR}" ]; then
+  echo >&2 "Error: missing environment variable HERO_TOOLCHAIN_DIR!"
+  exit 1
+fi
+source ${HERO_TOOLCHAIN_DIR}/env/hero_toolchain_env.sh
 
 RET=0
 if [ -z "${HERO_TARGET_HOST}" ]; then
-    echo "Error: HERO_TARGET_HOST environmental variables is missing!"
+    echo  >&2  "Error: HERO_TARGET_HOST environmental variables is missing!"
     RET=1
 fi
 if [ -z "${HERO_TARGET_PATH}" ]; then
-    echo "Error: HERO_TARGET_PATH environmental variables is missing!"
+    echo  >&2  "Error: HERO_TARGET_PATH environmental variables is missing!"
     RET=1
 fi
-if [ -z "${HERO_GCC_INSTALL_DIR}" ]; then
-    echo "Error: HERO_GCC_INSTALL_DIR environmental variables is missing!"
+if [ -z "${HERO_TOOLCHAIN_INSTALL_DIR}" ]; then
+    echo  >&2  "Error: HERO_TOOLCHAIN_INSTALL_DIR environmental variables is missing!"
     RET=1
 fi
 if [ "${RET}" -eq "0" ]; then
-    rsync -rctacvP ${HERO_GCC_INSTALL_DIR}/arm-linux-gnueabihf/lib/libgomp* ${HERO_TARGET_HOST}:${HERO_TARGET_PATH_LIB}/.
+    rsync -rctacvP ${HERO_TOOLCHAIN_INSTALL_DIR}/arm-linux-gnueabihf/lib/libgomp* ${HERO_TARGET_HOST}:${HERO_TARGET_PATH_LIB}/.
 fi
 
 exit $RET
diff --git a/bin/hero_toolchain_update_sources b/bin/hero_toolchain_update_sources
--- a/bin/hero_toolchain_update_sources
+++ b/bin/hero_toolchain_update_sources
@@ -15,8 +15,13 @@
 #
 # Authors: Alessandro Capotondi, University of Bologna (alessandro.capotondi@unibo.it)
 
-source ${HERO_TOOLCHAIN_DIR}/scripts/hero_arm_toolchain_env.sh
-source ${HERO_TOOLCHAIN_DIR}/scripts/hero_riscv32_toolchain_env.sh
+
+# Setup the envioronmental variables
+if [ -z "${HERO_TOOLCHAIN_DIR}" ]; then
+  echo >&2 "Error: missing environment variable HERO_TOOLCHAIN_DIR!"
+  exit 1
+fi
+source ${HERO_TOOLCHAIN_DIR}/env/hero_toolchain_env.sh
 
 get_submodules() {
     if [[ ! ${HERO_CI+x} ]]; then
@@ -28,7 +33,6 @@ get_submodules() {
             spath=$(git config -f .gitmodules --get submodule.$i.path)
             surl=$(git config -f .gitmodules --get submodule.$i.url)
             sbranch=$(git config -f .gitmodules --get submodule.$i.branch)
-            sha1=$(git rev-parse @:$spath)
             if [ -n "$(find "$spath" -maxdepth 0 -type d -empty 2>/dev/null)" ]; then
                 git clone --depth 1 $surl $spath -b $sbranch
             fi
@@ -38,29 +42,31 @@ get_submodules() {
 }
 
 get_sources() {
+    cd ${HERO_TOOLCHAIN_DIR}
+    
 	# Get submodules
 	get_submodules
 
 	# Get GCC prerequisites
-    cd ${HERO_ACCEL_GCC_SRC_DIR}
-    ${HERO_ACCEL_GCC_SRC_DIR}/contrib/download_prerequisites
+    cd ${HERO_TOOLCHAIN_GCC_SRC_DIR}
+    ${HERO_TOOLCHAIN_GCC_SRC_DIR}/contrib/download_prerequisites
     
 
     # Get Glibc for HOST
-    cd ${HERO_HOST_SRC_DIR} 
-    rm -rf $HERO_HOST_GLIBC
-    rm -rf $HERO_HOST_GLIBC.tar.xz
+    cd ${HERO_TOOLCHAIN_SRC_DIR} 
+    rm -rf $HERO_TOOLCHAIN_HOST_GLIBC
+    rm -rf $HERO_TOOLCHAIN_HOST_GLIBC.tar.xz
     {
-        wget --tries=1 --timeout=60 -nc http://mirror.switch.ch/ftp/mirror/gnu/glibc/$HERO_HOST_GLIBC.tar.xz
+        wget --tries=1 --timeout=60 -nc http://mirror.switch.ch/ftp/mirror/gnu/glibc/$HERO_TOOLCHAIN_HOST_GLIBC.tar.xz
     } || {
-        wget -nc https://ftp.gnu.org/gnu/glibc/$HERO_HOST_GLIBC.tar.xz
+        wget -nc https://ftp.gnu.org/gnu/glibc/$HERO_TOOLCHAIN_HOST_GLIBC.tar.xz
     }
     for f in *.tar*; do tar xfk $f; done
-    rm -rf $HERO_HOST_GLIBC.tar.xz
+    rm -rf $HERO_TOOLCHAIN_HOST_GLIBC.tar.xz
 }
 
 get_sources
 if [ $? -ne 0 ]; then
-	echo "ERROR: failed to get sources."
+	echo  >&2 "ERROR: failed to get sources."
     exit 1
 fi
